
  CREATE TABLE "LIMS"."SDG_LOG" 
   (	"SDG_ID" NUMBER(16,0) NOT NULL ENABLE, 
	"TIME" DATE NOT NULL ENABLE, 
	"APPLICATION_CODE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"SESSION_ID" NUMBER(16,0), 
	"DESCRIPTION" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIMS_TABLE" ;

  CREATE INDEX "LIMS"."IX_SDG_LOG_CODE" ON "LIMS"."SDG_LOG" ("APPLICATION_CODE", "TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIMS_INDEX" ;
  CREATE INDEX "LIMS"."IX_SDG_LOG_SDGID" ON "LIMS"."SDG_LOG" ("SDG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LIMS_TABLE" ;
